name: bnb-core Tests

on:
  pull_request:
    paths:
      - "packages/bnb-core/**"
      - "pnpm-lock.yaml"
      - "package.json"
      - ".github/workflows/bnb-core-prs.yml"
  push:
    branches:
      - main
    paths:
      - "packages/bnb-core/**"
      - "pnpm-lock.yaml"
      - "package.json"
      - ".github/workflows/bnb-core-prs.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: node and pnpm setup
        uses: pnpm/setup@v2
        with:
          runtime: node@24
          cache: true

      - name: Build bnb-core
        run: pnpm --filter bnb-core build

      - name: Run bnb-core tests with coverage
        run: pnpm --filter bnb-core test:coverage

      - name: Run bnb-core linting
        run: pnpm --filter bnb-core lint

      - name: Run bnb-core formatting check
        run: pnpm --filter bnb-core format

      - name: Upload coverage
        uses: codecov/codecov-action@v7
        with:
          files: ./packages/bnb-core/coverage/lcov.info
          flags: bnb-core
