name: All Tests

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "packages/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - ".github/workflows/test.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: node and pnpm setup
        uses: pnpm/setup@v2
        with:
          runtime: node@24
          cache: true

      - name: Build all packages
        run: pnpm build

      - name: Run all tests
        run: pnpm test

      - name: Generate coverage
        run: pnpm test:coverage

      - name: Run linting
        run: pnpm lint

      - name: Check formatting
        run: pnpm format

      - name: Upload coverage
        uses: codecov/codecov-action@v7
        with:
          files: ./packages/bnb-core/coverage/lcov.info
